---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  labels:
    app: pihole
    component: ""
    release: pihole
  name: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "managed-nfs-storage"
  resources:
    requests:
      storage: "1Gi"
