ssh_authorized_keys:
- github:username
hostname: hostname

k3os:
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  wifi:
  - name: ssid
    passphrase: passphrase
  password: password
  server_url: https://master_hostip:6443
  token: cluster_token
  labels:
    region: us-east-1
    system: rpi
